#logging.level.org.springframework=OFF
#logging.level.root=OFF
#spring.main.banner-mode=off
app:
  alfresco-properties:
    url: https://alfresco-nowo.cmas-systems.com
    username: config
    password: nowo123
  temp-folder: "C:\\Users\\Daniel Duarte\\Desktop\\Ecrypted\\OutPut"