server:
  port: 8964

wage-receipt-file-splitter:
  allowed-origins:
    - http://localhost:4200
  alfresco-properties:
    url: http://localhost:8080
    username: admin
    password: admin
  wage-receipts-nodeid: "35c3b08d-e0b6-4361-86e2-649b21d7e86e"

logging:
  level:
    com.cmas.systems.internship.receipts.splitter: debug
#    org.apache: trace
