server:
  port: 8964

wage-receipt-file-splitter:
  alfresco-properties:
    url: https://alfresco-nowo.cmas-systems.com
    username: config
    password: nowo123
  temp-folder: "C:\\Users\\Daniel Duarte\\Desktop\\Ecrypted\\OutPut"
  wage-receipts-nodeid: "7e2e7244-eeba-44c8-ba34-a02ad4bbf7ea"

logging:
  level:
    com.cmas.systems.internship.receipts.splitter: debug
