server:
  port: 8964

wage-receipt-file-splitter:
  allowed-origins:
    - http://localhost:4200
  alfresco-properties:
    url: http://alfresco.cmas-systems.local
    username: test_user
    password: Password123!
  wage-receipts-nodeid: "52f3d454-5ef6-4818-b861-61db814db56d"

logging:
  level:
    com.cmas.systems.internship.receipts.splitter: debug
#    org.apache: trace
